---
title: "Primer Taller big data"
author: "Julian Delgado Gutierrez"
date: "2025-02-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Taller 1



```{r cars}
load.lib <- c('data.table', 'plyr', 'doBy', 'outreg', 'margins', 'ggplot2', 
              'stargazer', 'tidyverse', 'dplyr', 'lubridate', 'ggthemes', 
              'plotly', 'haven', 'devtools', 'openxlsx', 'ggTimeSeries', 
              'gganimate', 'gifski', 'ggiraph', 'sf', 'stringr', 
              'rvest', 'rebus', 'purrr', 'tidytext', 'syuzhet', 
              'tokenizers', 'tm', 'wordcloud', 'cluster', 
              'topicmodels', 'SnowballC', 'pacman', 'skimr',
              'rio', 'gridExtra', 'corrplot', 'MASS','RSelenium','rvest','wdman')

install.lib <- load.lib[!load.lib %in% installed.packages()]
for(lib in install.lib) install.packages(lib) # ,dependencies=TRUE
sapply(load.lib, require, character = TRUE)

print("Librerías cargadas")


```

## Scrapping


```{r pressure, echo=FALSE}
url_base <- "https://ignaciomsarmiento.github.io/GEIH2018_sample/pages/geih_page_"

# Leer la primera página con nombres de columna
pagina <- read_html(paste0(url_base, "1.html"))
datos_totales <- pagina %>% html_table(fill = TRUE) %>% .[[1]]

# Iterar sobre las páginas 2 a 10 sin incluir los nombres de columna repetidos
for (i in 2:10) {
  url <- paste0(url_base, i, ".html")
  pagina <- read_html(url)
  tabla <- pagina %>% html_table(fill = TRUE) %>% .[[1]]
  
  # Unir los datos sin incluir la primera fila de la tabla (cabecera repetida)
  datos_totales <- bind_rows(datos_totales, tabla)
}

# Ver los primeros registros
head(datos_totales)

```

##limpieza


```{r pressure, echo=FALSE}
datos_totales <- as_tibble(datos_totales)

na_ingtot <- sum(is.na(datos_totales$ingtot))
na_age <- sum(is.na(datos_totales$age))
na_sex <- sum(is.na(datos_totales$sex))
na_totalHoursWorked <- sum(is.na(datos_totales$totalHoursWorked))
na_y_salary_m_hu <- sum(is.na(datos_totales$y_salary_m_hu))


# Crear un dataframe con los resultados
na_counts <- data.frame(
  Variable = c("ingtot", "age", "sex", "totalHoursWorked","y_salary_m_hu"),
  NAs = c(na_ingtot, na_age, na_sex, na_totalHoursWorked, na_y_salary_m_hu)
)

# Mostrar los resultados ordenados por cantidad de NA
na_counts <- na_counts %>% arrange(desc(NAs))
print(na_counts)

```


```{r pressure, echo=FALSE}
#Primer limpieza de datos enfocada en los NA
datos_filtrados <- datos_totales %>% filter(age >= 18, ingtot > 0, totalHoursWorked > 0, y_salary_m_hu > 0)
skim(datos_filtrados) %>% head()


```

```{r pressure, echo=FALSE}

na_ingtot <- sum(is.na(datos_filtrados$ingtot))
na_age <- sum(is.na(datos_filtrados$age))
na_sex <- sum(is.na(datos_filtrados$sex))
na_totalHoursWorked <- sum(is.na(datos_filtrados$totalHoursWorked))
na_y_salary_m_hu <- sum(is.na(datos_filtrados$y_salary_m_hu))


# Crear un dataframe con los resultados
na_counts <- data.frame(
  Variable = c("ingtot", "age", "sex", "totalHoursWorked","y_salary_m_hu"),
  NAs = c(na_ingtot, na_age, na_sex, na_totalHoursWorked, na_y_salary_m_hu)
)

# Mostrar los resultados ordenados por cantidad de NA
na_counts <- na_counts %>% arrange(desc(NAs))
print(na_counts)

```
##Filtrado Valores atipicos
```{r pressure, echo=FALSE}
# Boxplot de totalHoursWorked
ggplot(datos_filtrados, aes(y = totalHoursWorked)) +
  geom_boxplot() +
  labs(title = "Boxplot de Horas Trabajadas", y = "Horas Trabajadas")

# Boxplot de y_salary_m_hu
ggplot(datos_filtrados, aes(y = log(y_salary_m_hu))) +
  geom_boxplot() +
  labs(title = "Boxplot de Salario por Hora (Logaritmo Natural)", y = "ln(Salario por Hora)")
```
